site_name: Hirte Documentation

repo_url: https://github.com/containers/hirte
repo_name: hirte
edit_uri: blob/main/doc/docs/

copyright: © Red Hat
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - DBus API: 
    - Description: api/description.md
    - Examples: api/examples.md
  - Proxy Services: 
    - Concept: proxy/concept.md
  - Configuration files:
    - Hirte controller: man/hirte_conf.md
    - Hirte agent: man/hirte_agent_conf.md
  - Binaries:
    - hirte: man/hirte.md
    - hirte-agent: man/hirte-agent.md
    - hirtectl: man/hirtectl.md
    - hirte-proxy: man/hirte-proxy.md

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: True
  - sane_lists
  - smarty
  - admonition
  - pymdownx.snippets:
     base_path: ["doc"]
