site_name: BlueChi Documentation

repo_url: https://github.com/containers/bluechi
repo_name: bluechi
edit_uri: blob/main/doc/docs/

copyright: © Red Hat
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
  - DBus API: 
    - Description: api/description.md
    - Examples: api/examples.md
    - Bindings: api/bindings.md
  - Proxy Services: proxy_services.md
  - MAN Pages:
    - Binaries:
      - bluechi(1): man/bluechi.md
      - bluechi-agent(1): man/bluechi-agent.md
      - bluechi-proxy(1): man/bluechi-proxy.md
      - bluechictl(1): man/bluechictl.md
    - Configuration:
      - bluechi(5): man/bluechi_conf.md
      - bluechi-agent(5): man/bluechi_agent_conf.md

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: True
  - sane_lists
  - smarty
  - admonition
  - pymdownx.snippets:
     base_path: ["doc"]
     check_paths: True
