site_name: Hirte Documentation

repo_url: https://github.com/containers/hirte
repo_name: hirte
edit_uri: blob/main/doc/docs/

copyright: © Red Hat
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
  - DBus API: 
    - Description: api/description.md
    - Examples: api/examples.md
  - Proxy Services: 
    - Concept: proxy/concept.md
  - MAN Pages:
    - Binaries:
      - hirte(1): man/hirte.md
      - hirte-agent(1): man/hirte-agent.md
      - hirte-proxy(1): man/hirte-proxy.md
      - hirtectl(1): man/hirtectl.md
    - Configuration:
      - hirte(5): man/hirte_conf.md
      - hirte-agent(5): man/hirte_agent_conf.md

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: True
  - sane_lists
  - smarty
  - admonition
  - pymdownx.snippets:
     base_path: ["doc"]
