name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    name: cs9 x86_64 build
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    steps:
      - name: Enable additional repositories
        run: |
          dnf install -y dnf-plugin-config-manager

          # CRB is required for meson
          dnf config-manager -y --set-enabled crb

      - name: Install dependencies
        run: |
          dnf install \
                  gcc \
                  meson \
                  systemd-devel \
              -y

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Configure the build
        run: |
          meson setup builddir

      - name: Build the project
        run: |
          cd builddir
          meson compile

      - name: Execute tests
        run: |
          cd builddir
          meson test

      - name: Install artifacts
        run: |
          cd builddir
          meson install

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "/usr/local/bin/*"
