on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: cs9-build
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # Use githash of a tested commit instead of merge commit
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Report success
      run: |
        echo "Success :-)"
