name: Integration Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: cs9 x86_64 e2e
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y install podman

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: build hirte tests containers
        run: |
          podman run --rm --name hirte-builder \
            -v  ${PWD}:/hirte:Z -it \
            registry.gitlab.com/centos/automotive/sample-images/hirte/hirte-builder:1.0.0 \
            /bin/bash -c "API_BUS=user DESTDIR=bin make distclean install"
          podman build -f tests/Containerfile -t localhost/hirte-image:${{ github.event.pull_request.head.sha }} .

      - name: run hirte containers
        run: |
          podman network create --subnet 172.18.0.0/24 hirte-test
          podman run -d --rm --network hirte-test --ip 172.18.0.2 --name hirte-mgr -v ${PWD}/tests/e2e/manager.ini:/hirte/manager.ini:Z localhost/hirte-image:${{ github.event.pull_request.head.sha }}
          podman run -d --rm --network hirte-test --name hirte-agent-foo -v ${PWD}/tests/e2e/foo.ini:/hirte/agent.ini:Z localhost/hirte-image:${{ github.event.pull_request.head.sha }}
          podman run -d --rm --network hirte-test --name hirte-agent-bar -v ${PWD}/tests/e2e/bar.ini:/hirte/agent.ini:Z localhost/hirte-image:${{ github.event.pull_request.head.sha }}

      - name: run hirte orchestrator
        run: |
          podman exec -t  hirte-mgr \
            su - test-user -c  "(/usr/local/bin/hirte -c /hirte/manager.ini > mgr.log 2>&1 &)"

      - name: run hirte agent-bar
        run: |
          # Change node name in config file
          podman exec -t hirte-agent-bar \
            su - test-user -c "(/usr/local/bin/hirte-agent -c /hirte/agent.ini > bar.log 2>&1 &)"
          podman exec -it hirte-agent-bar /usr/bin/pkill --signal TERM hirte-agent
          podman exec -w /home/test-user -u test-user -it hirte-agent-bar \
            grep "Agent 'bar' connection attempt 0: success" bar.log

      - name: run hirte agent-foo
        run: |
          podman exec -t hirte-agent-foo \
            su - test-user -c  "(/usr/local/bin/hirte-agent -c /hirte/agent.ini > foo.log 2>&1 &)"
          podman exec -it hirte-agent-foo /usr/bin/pkill --signal TERM hirte-agent
          podman exec -w /home/test-user -u test-user -it hirte-agent-foo \
            grep "Agent 'foo' connection attempt 0: success" foo.log
