name: Integration Testing

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: cs9 x86_64 e2e
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
                  genisoimage \
                  libkrb5-dev \
                  libvirt-daemon-system \
                  libvirt-dev \
                  pkg-config \
                  podman \
                  qemu-kvm \
              -y

      - name: Install unpackaged python libraries from PyPi
        run: |
          pip install "tmt[provision]" "tmt[report-junit]" podman pytest

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rpm-artifacts
          path: 'tests/hirte-rpms'

      - name: Run integration tests
        run: |
          cd tests
          tmt run -eCONTAINER_USED=container-hirte-local

      - name: Show tmt log output in case of failure
        if: ${{ failure() }}
        run: |
          cat /var/tmp/tmt/run-001/log.txt

      - name: Gather tests artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: '/var/tmp/tmt'
