name: Integration Testing

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: cs9 x86_64 e2e
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
                  genisoimage \
                  libkrb5-dev \
                  libvirt-daemon-system \
                  libvirt-dev \
                  pkg-config \
                  podman \
                  qemu-kvm \
              -y

      - name: Install unpackaged python libraries from PyPi
        run: |
          pip install "tmt[provision]" "tmt[report-junit]" podman pytest

      - name: Checkout hirte-tests sources
        uses: actions/checkout@v3
        with:
          repository: 'mwperina/hirte-tests'
          path: 'hirte-tests'
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rpm-artifacts
          path: 'hirte-tests/hirte-rpms'

      - name: Run integration tests
        run: |
          cd hirte-tests
          tmt run -eCONTAINER_USED=container-hirte-local

      - name: Export logs from containers
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: '/var/tmp/tmt'


