name: lint-python
on:
  push:
    branches: [main]
    paths:
      - '**.py'
  pull_request:
    branches: [main]
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    steps:
      - name: Enable additional repositories
        run: |
          dnf install -y dnf-plugin-config-manager

          # EPEL is required for python3-flake8
          dnf install -y epel-release

      - name: Install dependencies
        run: |
          dnf install \
                  python3-flake8 \
              -y

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run flake8
        run: |
          find . -name '*.py' | xargs flake8

