name: Integration tests in multi-host mode

on:
  workflow_dispatch:
    inputs:
      composes:
        description: Name of the OS image to use
        required: true
        type: choice
        # based on:
        # https://api.dev.testing-farm.io/v0.1/composes
        options:
        - Fedora-37
        - Fedora-37-aarch64
        - Fedora-38
        - Fedora-38-aarch64
        - Fedora-39
        - Fedora-40
        - Fedora-40-aarch64
        - Fedora-latest
        - Fedora-latest-aarch64
        - Fedora-Rawhide
        - Fedora-Rawhide-aarch64
        - CentOS-7
        - CentOS-7-aarch64
        - CentOS-Stream-8
        - CentOS-Stream-8-aarch64
        - CentOS-Stream-9
        - CentOS-Stream-9-aarch64
        - CentOS-Stream-10

jobs:

  ghrelease:
    name: Run Integration Tests on testing farm in multihost mode
    runs-on: ubuntu-latest

    steps:
      - name: Start Integration Tests on testing farm
        uses: sclorg/testing-farm-as-github-action@v2.2.0
        with:
          api_key: ${{ secrets.TESTING_FARM_API_TOKEN }}
          git_url: https://github.com/eclipse-bluechi/bluechi.git
          git_ref: ${{ github.ref_name }}
          tf_scope: private
          tmt_path: tests
          tmt_plan_regex: multihost
          compose: ${{ inputs.composes }}
          pipeline_settings: '{"type": "tmt-multihost"}'
