name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/hirte/build-base:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Building hirte
        run: |
          make build

      - name: Running unit tests
        run: |
          make test-with-valgrind

      - name: Upload unit test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-logs
          path: ./builddir/meson-logs/testlog-valgrind.txt
