name: Unit tests

on:
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluechi/build-base:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Building BlueChi (with clang/LLVM)
        run: |
          export CC=clang
          export CXX=clang++
          meson setup builddir
          meson configure builddir
          meson compile -C builddir
          rm -rf builddir

      - name: Building BlueChi
        run: |
          meson setup builddir
          meson configure \
              -Db_coverage=true \
              -Dwith_analyzer=true \
            builddir
          meson compile -C builddir

      - name: Running unit tests
        run: |
          meson test --wrap='valgrind --leak-check=full --error-exitcode=1 --track-origins=yes' -C builddir

      - name: Generating coverage report (info)
        run: |
          ninja coverage -C builddir

      - name: Generating coverage report (html)
        run: |
          ninja coverage-html -C builddir
          
      - name: Move and rename coverage artifacts
        run: |
          mkdir -p /var/tmp/coverage
          mv builddir/meson-logs/coverage.info /var/tmp/coverage/unit-test-coverage.info
          
          mkdir -p /var/tmp/coverage/unit-test-report
          mv builddir/meson-logs/coveragereport/* /var/tmp/coverage/unit-test-report/

      - name: Upload unit test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-logs
          path: ./builddir/meson-logs/testlog-valgrind.txt

      - name: Upload coverage artifact (info)
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage-info
          path: /var/tmp/coverage/unit-test-coverage.info
          if-no-files-found: error

      - name: Upload coverage artifact (html)
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage-html
          path: /var/tmp/coverage/unit-test-report/
          if-no-files-found: error

      - name: Report coverage results
        run: |
          cd /var/tmp/coverage/unit-test-report/
          html2text --ignore-images --ignore-links -b 0 --bypass-tables index.html >> $GITHUB_STEP_SUMMARY
